# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/neodeng"
  weibo: "http://weibo.com/u/5323510820"
  #rss: "#"
  #facebook: "#"
  google: "https://plus.google.com/u/0/107158690205371195391"
  # twitter: "#"
  # linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous

favicon: /favicon.ico

#你的头像
avatar: /dyq.jpg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称
duoshuo: "neodeng"
#是否开启云标签
tagcloud: true